# Generated by Django 4.0.1 on 2022-01-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200)),
                ('sana', models.DateField()),
                ('mavzu', models.CharField(max_length=300)),
                ('matn', models.TextField()),
                ('muallif', models.CharField(max_length=100)),
            ],
        ),
    ]
